#line 1 "newt.l.c"

#line 3 "newt.l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, yy_size_t size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (yy_size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[230] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   22,   22,
        0,    0,    2,    2,    7,    7,    0,    0,   60,   55,
       27,   26,   26,   39,   55,   32,   31,   30,   55,   31,
       51,   51,   55,   55,   34,   34,   34,   55,   40,   40,
       55,   27,   55,   17,   17,   16,   16,   17,   58,   57,
       57,   58,   19,   19,   20,   59,   22,   21,   21,   23,
       59,   25,   24,    5,    2,    4,    4,    5,   10,    7,
        9,    9,    8,   11,   12,   12,   27,   26,    0,   38,
        0,   47,    0,   32,    0,    0,   14,    0,    0,   53,
       51,    0,   36,   37,    0,    0,    0,   18,   33,   34,

       48,   49,    0,   40,   40,    0,    0,   41,   27,    0,
        0,    0,    0,   16,   15,   57,    0,   19,   22,    0,
       21,   22,   24,    2,    4,    0,    3,    7,    9,    8,
       11,   12,    0,   43,    0,    0,    0,   35,    0,   42,
        0,    0,   13,    0,   42,    0,    0,   53,    0,   52,
        0,    0,   49,    0,    0,   50,   40,   40,    0,    0,
        0,   56,    0,    0,    0,    0,   44,    0,    0,    0,
        0,    0,   42,    0,    0,    0,    0,    0,   53,    0,
       40,   40,    0,    0,    0,    0,    0,    0,   42,    0,
        0,    0,    0,    0,    0,   54,   40,   40,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   40,   40,
        0,    6,   22,    0,   46,   45,    0,    0,    0,   40,
       40,    0,    0,    0,   28,   29,    0,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    4,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,   12,   11,   11,
       11,   13,   14,   11,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,   28,   29,
       30,   30,   31,   30,   30,   32,   30,   33,   30,   30,
       30,   30,   34,   30,   30,   30,   30,   30,   30,   30,
       11,   35,   11,   11,   36,   11,   27,   27,   37,   38,

       39,   27,   30,   30,   40,   30,   30,   41,   30,   42,
       30,   30,   30,   43,   44,   43,   45,   30,   30,   46,
       30,   30,   11,   47,   48,   11,   48,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    2,    3,    4,    4,    5,    5,    6,    5,    5,
        5,    5,    7,    5,    5,    5,    8,    9,    9,    5,
        5,    7,    5,    7,    5,    5,   10,   10,   10,   11,
       11,   11,   11,   11,   12,   13,   10,   10,   10,   11,
       11,   11,   11,   11,   11,   11,   14,    7,   15
    } ;

static const flex_int16_t yy_base[274] =
    {   0,
        0,   47,   54,   58,   47,   61,   50,   72,   78,   83,
      115,  158,   89,   95,  102,  106,   64,   68,  524,  834,
      111,  834,  519,   81,  487,  509,  834,  834,  501,  115,
      117,  111,   79,  166,  117,  493,   99,  119,    0,  479,
      129,  171,  172,  834,  834,  834,  510,  496,  834,  834,
      508,  504,  834,  501,  144,  834,  469,  834,  499,  834,
      176,  834,    0,  834,  128,  834,  498,  493,  834,  176,
      834,  496,  188,    0,  834,  495,  211,  834,  173,  834,
      207,  834,  245,  834,  479,  148,  834,  490,  212,  204,
      209,    0,  834,  834,  230,  272,  198,  834,  834,  834,

      191,    0,  191,    0,  208,  209,  213,  834,  262,  264,
      288,  451,  452,  834,  834,  834,  487,  834,  455,  278,
      834,  454,    0,  290,  834,  475,  834,  295,  834,  227,
        0,  834,  271,  834,    0,    0,    0,  834,  224,  264,
      295,  478,  834,  275,  280,  299,  328,  330,  299,    0,
      347,  217,    0,  284,  289,  834,  450,  442,  424,  409,
      431,  834,    0,  372,    0,  369,  834,    0,    0,  291,
      292,  308,  337,  353,  381,  403,  370,  314,  341,  334,
      369,  364,  340,  300,    0,    0,    0,    0,  834,    0,
      290,  425,  394,  447,    0,  834,  294,  274,  240,  365,

        0,    0,    0,    0,    0,  469,    0,  491,  230,  195,
      178,  371,  138,  356,  834,  834,    0,  513,    0,  115,
       79,   51,  359,    0,    0,    0,  376,  377,  834,  552,
      567,  582,  597,  612,  627,  642,  655,  666,  681,  688,
      694,  703,  715,  374,  729,  744,  757,  772,  380,  779,
      788,  802,  809,  816,  383,  394,  397,  414,  416,  418,
      424,  821,  436,  438,  440,  446,  448,  450,  458,  460,
      462,  468,  470
    } ;

static const flex_int16_t yy_def[274] =
    {   0,
      229,    1,  230,  230,  231,  231,    1,    1,  232,  232,
      233,  233,  234,  234,  235,  235,  236,  236,  229,  229,
      229,  229,  229,  237,  238,  229,  229,  229,  229,  239,
      229,  229,  229,  229,  229,  229,  229,  240,  241,  241,
      242,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  243,  229,  229,  229,
      229,  229,  244,  229,  229,  229,  229,  245,  229,  229,
      229,  229,  229,  246,  229,  229,  229,  229,  237,  229,
      229,  229,  229,  229,  229,  247,  229,  248,  247,  229,
      229,  249,  229,  229,  229,  229,  229,  229,  229,  229,

      229,  250,  251,  241,  241,  242,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  252,  229,  243,  229,
      229,  253,  244,  229,  229,  245,  229,  229,  229,  229,
      246,  229,  254,  229,  255,  256,  257,  229,  247,  247,
      229,  248,  229,  247,  247,  247,  247,  229,  229,  249,
      229,  229,  250,  251,  229,  229,  241,  241,  229,  229,
      252,  229,  258,  229,  259,  229,  229,  260,  261,  247,
      262,  247,  247,  247,  147,  147,  229,  229,  229,  229,
      241,  241,  229,  229,  263,  264,  265,  266,  229,  267,
      229,  176,  229,  176,  175,  229,  241,  241,  229,  229,

      268,  269,  270,  271,  272,  176,  175,  176,  241,  241,
      229,  229,  253,  254,  229,  229,  273,  176,  147,  241,
      241,  229,  262,  175,  241,  241,  229,  229,    0,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229
    } ;

static const flex_int16_t yy_nxt[884] =
    {   0,
       20,   20,   21,   22,   23,   21,   20,   24,   20,   25,
       20,   26,   27,   28,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   20,   38,   39,   39,   39,   39,
       39,   39,   39,   39,   20,   40,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   41,   20,   20,   42,
       50,   51,   42,   53,   54,   43,   45,   46,   47,   45,
       45,   46,   47,   45,   50,   51,   48,   75,   76,   52,
       48,   75,   76,   55,   42,   53,   54,   42,   56,   56,
       43,   58,   59,   56,   56,   60,   58,   59,   80,  227,
       60,   65,   66,   67,   65,   55,   68,   65,   66,   67,

       65,   93,   68,   94,   70,   71,   72,   70,   70,   71,
       72,   70,   61,   77,  226,   81,   77,   61,   56,   73,
       73,  100,   99,   73,   73,   98,   90,   87,   91,   91,
      124,   88,   90,  124,   91,   91,  101,  101,   99,  100,
      100,   63,   63,   63,   63,   63,   63,   63,   63,   89,
      225,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   56,   92,  107,  140,  103,  100,   99,   95,   95,
       96,   95,  164,  109,  111,  108,  109,  111,  128,  110,
       80,  128,  141,  119,   63,   63,   63,   63,   63,   63,
       63,   63,  119,   97,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   97,  130,  130,   81,  101,  101,
      119,  112,  113,   77,   79,  222,   77,  119,  119,  144,
      122,  148,  148,   79,   90,  155,   91,   91,  145,  152,
      221,  149,   95,   95,   96,   95,  157,  156,  152,  158,
      140,   79,  149,  107,  130,  130,  146,  106,   79,   79,
      180,  133,  134,  144,  144,  108,  147,   97,  141,  106,
      180,  134,  135,  135,  109,  220,  111,  109,   97,  111,
      110,  135,  135,  135,   95,  151,   96,   95,   80,  134,
      140,  135,  135,  135,  211,  119,  134,  134,  136,  137,
      111,  140,  124,  111,  119,  124,  140,  128,  141,   97,

      128,  210,  170,  112,  113,  166,  172,  140,  189,  141,
       97,  170,  119,  178,  141,  173,  179,  179,  155,  119,
      119,  209,  122,  154,  140,  141,  191,  112,  113,  170,
      156,  179,  179,  174,  170,  154,  170,  170,  200,  171,
      172,  172,  141,  175,  140,  176,  176,  148,  148,   95,
       95,   96,   95,  140,  176,  176,  176,  149,  179,  179,
      172,  196,  177,   80,  176,  176,  176,  212,  149,  173,
      212,  141,  196,  212,   97,  189,  212,  170,  228,  228,
      199,  228,  228,  123,  123,   97,  170,  174,  150,  150,
      166,  167,  167,  191,  172,  172,  198,  175,  192,  192,

      197,  170,  168,  168,  170,  169,  169,  192,  192,  192,
      170,  170,  170,   79,  195,  193,  119,  192,  192,  192,
      194,  194,  185,  185,  186,  186,  187,  187,  170,  194,
      194,  194,  188,  188,  162,  170,  170,  141,  207,  194,
      194,  194,  206,  206,  201,  201,  202,  202,  203,  203,
      184,  206,  206,  206,  204,  204,  205,  205,  213,  213,
      183,  206,  206,  206,  208,  208,  214,  214,  215,  215,
      216,  216,  182,  208,  208,  208,  217,  217,  223,  223,
      181,  143,  127,  208,  208,  208,  218,  218,  164,  120,
      162,  160,  159,  143,  138,  218,  218,  218,  132,  129,

      127,  125,  121,  120,  118,  218,  218,  218,  219,  219,
      117,  116,  115,  114,  105,  100,   85,  219,  219,  219,
       84,   83,   78,  229,  229,  229,  229,  219,  219,  219,
      224,  224,  229,  229,  229,  229,  229,  229,  229,  224,
      224,  224,  229,  229,  229,  229,  229,  229,  229,  224,
      224,  224,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   79,  229,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,  102,  102,  102,  229,

      102,  102,  104,  104,  104,  229,  104,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  119,  229,  119,
      229,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      126,  229,  229,  126,  126,  229,  126,  126,  126,  126,
      126,  126,  229,  126,  131,  131,  131,  229,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  139,
      229,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  153,  153,  153,
      229,  153,  154,  154,  154,  154,  154,  154,  154,  154,

      154,  154,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  163,  163,  229,
      163,  165,  229,  229,  165,  165,  229,  165,  190,  190,
      190,  229,  190,   19,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229
    } ;

static const flex_int16_t yy_chk[884] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        5,    5,    2,    7,    7,    2,    3,    3,    3,    3,
        4,    4,    4,    4,    6,    6,    3,   17,   17,    6,
        4,   18,   18,    7,    8,    8,    8,    8,    9,    9,
        8,    9,    9,   10,   10,    9,   10,   10,   24,  222,
       10,   13,   13,   13,   13,    8,   13,   14,   14,   14,

       14,   33,   14,   33,   15,   15,   15,   15,   16,   16,
       16,   16,    9,   21,  221,   24,   21,   10,   11,   15,
       15,   37,   37,   16,   16,   35,   32,   30,   32,   32,
       65,   30,   31,   65,   31,   31,   38,   38,   35,   35,
       35,   11,   11,   11,   11,   11,   11,   11,   11,   30,
      220,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   12,   31,   41,   86,   38,   55,   55,   34,   34,
       34,   34,  213,   42,   43,   41,   42,   43,   70,   42,
       79,   70,   86,   61,   12,   12,   12,   12,   12,   12,
       12,   12,   61,   34,   12,   12,   12,   12,   12,   12,

       12,   12,   12,   12,   34,   73,   73,   79,  101,  101,
       61,   43,   43,   77,   81,  211,   77,   61,   61,   89,
       61,   90,   90,   81,   91,  103,   91,   91,   89,   97,
      210,   90,   95,   95,   95,   95,  105,  103,   97,  105,
      139,   81,   90,  106,  130,  130,   89,  107,   81,   81,
      152,   81,   83,   89,   89,  106,   89,   95,  139,  107,
      152,   83,   83,   83,  109,  209,  110,  109,   95,  110,
      109,   83,   83,   83,   96,   96,   96,   96,  133,   83,
      140,   83,   83,   83,  199,  120,   83,   83,   83,   83,
      111,  144,  124,  111,  120,  124,  145,  128,  140,   96,

      128,  198,  141,  110,  110,  133,  146,  170,  171,  144,
       96,  141,  120,  149,  145,  146,  149,  149,  154,  120,
      120,  197,  120,  155,  172,  170,  171,  111,  111,  141,
      154,  178,  178,  146,  191,  155,  141,  141,  184,  141,
      146,  146,  172,  146,  147,  147,  147,  148,  148,  151,
      151,  151,  151,  173,  147,  147,  147,  148,  179,  179,
      174,  180,  147,  214,  147,  147,  147,  200,  148,  174,
      200,  173,  180,  212,  151,  223,  212,  177,  227,  228,
      183,  227,  228,  244,  244,  151,  177,  174,  249,  249,
      214,  255,  255,  223,  174,  174,  182,  174,  175,  175,

      181,  193,  256,  256,  177,  257,  257,  175,  175,  175,
      193,  177,  177,  166,  177,  175,  164,  175,  175,  175,
      176,  176,  258,  258,  259,  259,  260,  260,  193,  176,
      176,  176,  261,  261,  161,  193,  193,  176,  193,  176,
      176,  176,  192,  192,  263,  263,  264,  264,  265,  265,
      160,  192,  192,  192,  266,  266,  267,  267,  268,  268,
      159,  192,  192,  192,  194,  194,  269,  269,  270,  270,
      271,  271,  158,  194,  194,  194,  272,  272,  273,  273,
      157,  142,  126,  194,  194,  194,  206,  206,  122,  119,
      117,  113,  112,   88,   85,  206,  206,  206,   76,   72,

       68,   67,   59,   57,   54,  206,  206,  206,  208,  208,
       52,   51,   48,   47,   40,   36,   29,  208,  208,  208,
       26,   25,   23,   19,    0,    0,    0,  208,  208,  208,
      218,  218,    0,    0,    0,    0,    0,    0,    0,  218,
      218,  218,    0,    0,    0,    0,    0,    0,    0,  218,
      218,  218,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  233,  233,  233,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  237,    0,  237,
      237,  237,  237,  237,  237,  237,  237,  237,  237,  237,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  240,  240,  240,    0,

      240,  240,  241,  241,  241,    0,  241,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  243,    0,  243,
        0,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      245,    0,    0,  245,  245,    0,  245,  245,  245,  245,
      245,  245,    0,  245,  246,  246,  246,    0,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  247,
        0,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  250,  250,  250,
        0,  250,  251,  251,  251,  251,  251,  251,  251,  251,

      251,  251,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  253,  253,    0,
      253,  254,    0,    0,  254,  254,    0,  254,  262,  262,
      262,    0,  262,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static size_t yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "newt.l"
/*------------------------------------------------------------------------*/
/**
 * @file	newt.l
 * @brief   字句解析
 *
 * @author  M.Nukui
 * @date	2003-11-07
 *
 * Copyright (C) 2003-2004 M.Nukui All rights reserved.
 */
/*
%option interactive
*/
#line 20 "newt.l"

/* ヘッダファイル */
#include <string.h>

#include "NewtErrs.h"
#include "NewtObj.h"
#include "NewtEnv.h"
#include "NewtParser.h"
#include "NewtPrint.h"
#include "NewtIO.h"

#include "lookup_words.h"
#include "yacc.h"
#include "y.tab.h"


/* 関数プロトタイプ */
static int			lex_update_tokenpos(int op);
static void			lex_newline(void);

static char *		lex_truncstr(char *s);
static char *		lex_escapestr(char *s);
static char			lex_escapechar(char c);
static int          lex_htoi(char *s, int len);
static uint64_t     lex_htoll(char *s, int len);
static uint32_t		lex_getop(char *s);
static int			lex_op(char *s, int op);
static int			lex_reserveword(int tokn, char *s);

static int			lex_makesymbol(char *s, bool trunc);
static int			lex_makestring(char *s, bool trunc);
static int			lex_makeregex(char *s, bool trunc);
static int          lex_makechar(int c);
static int          lex_makespecial(int c);
static int			lex_makeinteger(int64_t n);
static int			lex_makereal(double n);

static int			lex_makemagicpointer(int n);
static int			lex_makenamedmp(char *s, bool trunc);

static int          lex_include_file(char *s);
static void         lex_include_invalid_filename(void);
static int          lex_include_done(void);
static void         lex_include_pop(void);

static int          lex_set_line(char *s);
static void         lex_invalid_line(void);

static void			lex_debug(int type);

#define MAX_INCLUDE_DEPTH 10
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
/* yyin of each including file: NPSParseFile reuses one flex buffer for every
   file and only replaces yyin, so the buffer's own FILE may be stale. */
FILE * include_files[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;

/* マクロ */
#undef YY_INPUT
/* An included file is read from its own FILE, even while compiling a string. */
#define YY_INPUT(b, r, ms) (r = (0 < include_stack_ptr) ? \
    (int)fread(b, 1, ms, yyin) : nps_yyinput(yyin, b, ms))

#define WORN_NOS2(msg)		if (NEWT_MODE_NOS2) NPSErrorStr('W', msg);

#line 805 "newt.l.c"

#line 807 "newt.l.c"

#define INITIAL 0
#define COMMENT 1
#define SHELL 2
#define BINARY 3
#define STRING 4
#define REGEX 5
#define INCL 6
#define LINE 7
#define SKIPLINE 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 120 "newt.l"



#line 124 "newt.l"
    if (nps_env.first_time)
    {   //初回起動時
        nps_env.first_time = false;
        BEGIN SHELL;
    }


                                /* allow "C" style including of more script files */
#line 1048 "newt.l.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 230 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 834 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 132 "newt.l"
{ BEGIN INCL; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 133 "newt.l"
/* eat the whitespace */
	YY_BREAK
/* read the file name in double quotes */
case 3:
YY_RULE_SETUP
#line 135 "newt.l"
lex_include_file(yytext);
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 136 "newt.l"
{ lex_include_invalid_filename(); yyless(0); BEGIN INITIAL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 137 "newt.l"
{ lex_include_invalid_filename(); BEGIN SKIPLINE; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(SHELL):
case YY_STATE_EOF(BINARY):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(REGEX):
case YY_STATE_EOF(INCL):
case YY_STATE_EOF(LINE):
case YY_STATE_EOF(SKIPLINE):
#line 138 "newt.l"
if (lex_include_done()==0) return 0;
	YY_BREAK
/* allow '#line n' to change current line number */
case 6:
YY_RULE_SETUP
#line 141 "newt.l"
{ BEGIN LINE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 142 "newt.l"
/* eat the whitespace */
	YY_BREAK
/* read the line number */
case 8:
YY_RULE_SETUP
#line 144 "newt.l"
lex_set_line(yytext);
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 145 "newt.l"
{ lex_invalid_line(); yyless(0); BEGIN INITIAL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 146 "newt.l"
{ lex_invalid_line(); BEGIN SKIPLINE; }
	YY_BREAK
/* skip the rest of a line with a bad directive */
case 11:
YY_RULE_SETUP
#line 149 "newt.l"
BEGIN INITIAL;
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 150 "newt.l"
{ yyless(0); BEGIN INITIAL; }
	YY_BREAK
case 13:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 153 "newt.l"

	YY_BREAK
case 14:
YY_RULE_SETUP
#line 155 "newt.l"
{
									BEGIN COMMENT;
									lex_update_tokenpos(0);
								}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 160 "newt.l"
{
									BEGIN INITIAL;
									lex_update_tokenpos(0);
								}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 165 "newt.l"
lex_newline();
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 166 "newt.l"
lex_update_tokenpos(0);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 168 "newt.l"
{
									BEGIN BINARY;
									return lex_update_tokenpos(kBINBG);
								}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 173 "newt.l"
lex_newline();
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 174 "newt.l"
{
									BEGIN INITIAL;
									return lex_update_tokenpos(kBINED);
								}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 179 "newt.l"
{
									nps_env.lineno++;
									yymore();
								}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 184 "newt.l"
yymore();
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 185 "newt.l"
{
									BEGIN INITIAL;
									return lex_makestring(yytext, true);
								}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 190 "newt.l"
{ return lex_makestring(yytext, false); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 191 "newt.l"
{
									unput(*yytext);
									BEGIN INITIAL;
								}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 196 "newt.l"
lex_newline();
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 197 "newt.l"
lex_update_tokenpos(0);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 199 "newt.l"
{ return lex_makestring((char *)(nps_env.fname?nps_env.fname:"-"), false); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 200 "newt.l"
{ return lex_makeinteger(nps_env.lineno); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 202 "newt.l"
{ return lex_op(yytext, kADDOP); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 203 "newt.l"
{ return lex_op(yytext, kMULOP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 204 "newt.l"
{ return lex_op(yytext, kSTROP); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 205 "newt.l"
{ return lex_op(yytext, kSFTOP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 206 "newt.l"
{ return lex_op(yytext, kRELOP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 207 "newt.l"
{ return lex_update_tokenpos(k3READER); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 209 "newt.l"
{ return lex_update_tokenpos(kASNOP); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 210 "newt.l"
{ return lex_update_tokenpos(kSNDOP); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 212 "newt.l"
{ return lex_makestring(yytext, true); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 214 "newt.l"
{
									BEGIN STRING;
									yymore();
								}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 219 "newt.l"
{ return lex_makesymbol(yytext, false); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 220 "newt.l"
{ return lex_makesymbol(yytext, true); }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 222 "newt.l"
{
									BEGIN REGEX;
									return lex_makeregex(yytext, true);
								}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 227 "newt.l"
{ return lex_makechar(lex_escapechar(yytext[2])); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 228 "newt.l"
{ return lex_makechar(lex_htoi(yytext + 2, -1)); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 229 "newt.l"
{ return lex_makechar(lex_htoi(yytext + 3, -1)); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 230 "newt.l"
{ return lex_makespecial(lex_htoi(yytext + 3, -1)); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 231 "newt.l"
{ return lex_makechar(yytext[1]); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 233 "newt.l"
{ return lex_makemagicpointer(atoi(yytext + 1)); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 234 "newt.l"
{ return lex_makenamedmp(yytext + 1, false); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 235 "newt.l"
{ return lex_makenamedmp(yytext + 1, true); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 237 "newt.l"
{ return lex_makeinteger(atoll(yytext)); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 238 "newt.l"
{ return lex_makeinteger(lex_htoll(yytext + 2, -1)); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 240 "newt.l"
{ return lex_makereal(atof(yytext)); }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 242 "newt.l"
{ return lex_update_tokenpos(kELSE); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 244 "newt.l"
{ return lex_update_tokenpos(yytext[0]); }
	YY_BREAK
/* if the very first line starts witha "shebang" (#!),
                                 * Unix shells will run the tool indicated following the #! */
/* if the line starts with #!, ignore the entire line, then start parsing */
case 56:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 249 "newt.l"
{ BEGIN INITIAL; }
	YY_BREAK
/* if the line is empty, count it and start parsing */
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 251 "newt.l"
{ lex_newline(); BEGIN INITIAL; }
	YY_BREAK
/* any other character on the input line will unread it and start parsing */
case 58:
YY_RULE_SETUP
#line 253 "newt.l"
{ unput(*yytext); yy_set_bol(1); BEGIN INITIAL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 255 "newt.l"
ECHO;
	YY_BREAK
#line 1471 "newt.l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		size_t yy_amount_of_matched_text = yy_cp - (yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_c_buf_p) - (yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			yy_size_t yy_c_buf_p_offset =
				(yy_c_buf_p) - b->yy_ch_buf;

			if ( b->yy_is_our_buffer )
				{
				if ( b->yy_buf_size < (SIZE_MAX - 2) / 2 )
					b->yy_buf_size *= 2;
				else
					b->yy_buf_size = SIZE_MAX - 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = new_size - 2;
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 230 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 230 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 229);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += dest - source;
		yy_bp += dest - source;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Prevent overflow in calculation of n below */
	if ( _yybytes_len > SIZE_MAX - 2 )
		YY_FATAL_ERROR( "bad length in yy_scan_bytes()" );
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 255 "newt.l"



/// 一部の lex で YY_FLUSH_BUFFER が undef されてしまう問題に対応
#ifndef YY_FLUSH_BUFFER
	#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )
#endif


/// 予約語
static keyword_t	reserved_words[] = {
		// アルファベット順にソートしておくこと
		{"AND",			kANDOP},		// 予約語
        {"BEGIN",		kBEGIN},		// 予約語
        {"BREAK",		kBREAK},		// 予約語
        {"BY",			kBY},			// 予約語
        {"CALL",		kCALL},			// 予約語
//		{"COLLECT",		kCOLLECT},
        {"CONSTANT",	kCONSTANT},		// 予約語
//		{"DEEPLY",		kDEEPLY},
        {"DIV",			kMULOP},		// 予約語
        {"DO",			kDO},			// 予約語
        {"ELSE",		kELSE},			// 予約語
        {"END",			kEND},			// 予約語
        {"EXISTS",		kEXISTS},		// 予約語
        {"FOR",			kFOR},			// 予約語
        {"FOREACH",		kFOREACH},		// 予約語
        {"FUNC",		kFUNC},			// 予約語
        {"GLOBAL",		kGLOBAL},		// 予約語
        {"IF",			kIF},			// 予約語
        {"IN",			kIN},			// 予約語
        {"INHERITED",	kINHERITED},	// 予約語
        {"LOCAL",		kLOCAL},		// 予約語
        {"LOOP",		kLOOP},			// 予約語
        {"MOD",			kMULOP},		// 予約語
        {"NATIVE",		kNATIVE},		// 予約語
        {"NIL",			kNIL},
        {"NOT",			kNOTOP},		// 予約語
        {"ONEXCEPTION",	kONEXCEPTION},	// 予約語
        {"OR",			kOROP},			// 予約語
        {"REPEAT",		kREPEAT},		// 予約語
        {"RETURN",		kRETURN},		// 予約語
        {"SELF",		kSELF},			// 予約語
        {"THEN",		kTHEN},			// 予約語
        {"TO",			kTO},			// 予約語
        {"TRUE",		kTRUE},
        {"TRY",			kTRY},			// 予約語
        {"UNTIL",		kUNTIL},		// 予約語
        {"WHILE",		kWHILE},		// 予約語
        {"WITH",		kWITH},			// 予約語
    };

/// オペレータ
static keyword_t	operator_words[] = {
		// アルファベット順にソートしておくこと
        {"&&",			kNPS_CONCAT2},
        {"<<",			kNPS_SHIFT_LEFT},
        {"<=",			kNPS_LESS_EQUAL},
        {"<>",			kNPS_NOT_EQUAL},
        {"==",			kNPS_OBJECT_EQUAL},
        {">=",			kNPS_GREATER_EQUAL},
        {">>",			kNPS_SHIFT_RIGHT},
	};


/*------------------------------------------------------------------------*/
/** トークンの位置を更新
 *
 * @param op		[in] オペレータ
 *
 * @return			オペレータをそのまま返す
 */

int lex_update_tokenpos(int op)
{
	strncat(nps_env.linebuf, yytext, sizeof(nps_env.linebuf));

	nps_env.tokenpos += yyleng;
	nps_env.yyleng = yyleng;
	return op;
}


/*------------------------------------------------------------------------*/
/** 新しい行の初期化
 *
 * @return			なし
 *
 * @note			エラー箇所を適切に表示するために入力行を保持する
 */

void lex_newline(void)
{
	uint32_t	n = 1;

	if (yytext[0] == '\r' && yytext[1] == '\n')
		n++;

	nps_env.linebuf[0] = '\0';
	nps_env.tokenpos = 0;
	nps_env.yyleng = 0;
	nps_env.lineno++;
	yyless(n);
}


/*------------------------------------------------------------------------*/
/** 文字列の前後１文字を切り詰める
 *
 * @param s			[in] 文字列
 *
 * @return			切り詰めたられた文字列
 */

char * lex_truncstr(char *s)
{
    s[strlen(s) - 1] = '\0';

    return s + 1;
}


/*------------------------------------------------------------------------*/
/** エスケープされた文字列を処理する
 *
 * @param s			[in] エスケープされた文字列
 *
 * @return			文字列
 */

char * lex_escapestr(char *s)
{
    int		uni = 0;
    char *	src;
    char *	dst;

    dst = src = s;

    while (*src)
    {
        if (*src =='\\')
        {
            src++;

            if (*src == 'u')
            {
                uni = ! uni;
            }
            else
            {
              	*dst = lex_escapechar(*src);
                dst++;
            }

            src++;
        }
        else if (uni)
        {
/*
            *dst = lex_htoi(src, 4);
            src += 4;
            dst++;
*/
            *dst = lex_htoi(src, 2);
            src += 2;
            dst++;

            *dst = lex_htoi(src, 2);
            src += 2;
            dst++;
        }
        else
        {
            if (dst != src)
                *dst = *src;

            dst++;
            src++;
        }
    }

    *dst = '\0';

    return s;
}


/*------------------------------------------------------------------------*/
/** エスケープ文字を処理する
 *
 * @param c			[in] エスケープ文字
 *
 * @return			文字
 */

char lex_escapechar(char c)
{
    switch (c)
    {
        case 'n':
            c = '\n';
            break;

        case 'r':
            c = '\r';
            break;

        case 't':
            c = '\t';
            break;
    }

    return c;
}


/*------------------------------------------------------------------------*/
/** 16進数文字列を整数に変換
 *
 * @param s			[in] 16進数文字列
 * @param len		[in] 16進数文字列の長さ
 *
 * @return			整数
 */
int lex_htoi(char *s, int len)
{
    int	n = 0;

    if (len < 0)
        len = (int)strlen(s) + 1 + len;

    while (0 < len)
    {
        n *= 16;

        if ('A' <= *s && *s <= 'F')
            n += *s - 'A' + 10;
        else if ('a' <= *s && *s <= 'f')
            n += *s - 'a' + 10;
        else
            n += *s - '0';

        s++;
        len--;
    }

    return n;
}


/*------------------------------------------------------------------------*/
/** 64 bit version of reading a hexadecimal number
 */
uint64_t lex_htoll(char *s, int len)
{
    uint64_t n = 0;

    if (len < 0)
    len = (int)strlen(s) + 1 + len;

    while (0 < len)
    {
        n *= 16;

        if ('A' <= *s && *s <= 'F')
        n += *s - 'A' + 10;
        else if ('a' <= *s && *s <= 'f')
        n += *s - 'a' + 10;
        else
        n += *s - '0';

        s++;
        len--;
    }

    return n;
}


/*------------------------------------------------------------------------*/
/** オペレータ文字列からオペレータIDを求める
 *
 * @param s			[in] オペレータ文字列
 *
 * @return			オペレータID
 */

uint32_t lex_getop(char *s)
{
    uint32_t	op;
    int	len;

	len = (int)strlen(s);

    if (len == 1)
    {
        op = s[0];
    }
    else
    {
        int	wlen;

        wlen = sizeof(operator_words) / sizeof(keyword_t);
        op = lookup_words(operator_words, wlen, s);
    }

    return op;
}


/*------------------------------------------------------------------------*/
/** オペレータトークンの作成
 *
 * @param s			[in] オペレータ文字列
 *
 * @return			トークンID
 */

int lex_op(char *s, int op)
{
    yylval.op = lex_getop(yytext);
	return lex_update_tokenpos(op);
}


/*------------------------------------------------------------------------*/
/** 予約語のトークンを作成
 *
 * @param tokn		[in] トークンID
 * @param s			[in] オペレータ文字列
 *
 * @return			トークンID
 */

int lex_reserveword(int tokn, char *s)
{
    switch (tokn)
    {
        case kMULOP:
            if (strcasecmp(s, "div") == 0)
                yylval.op = kNPS_DIV;
            else if (strcasecmp(s, "mod") == 0)
                yylval.op = kNPS_MOD;
            break;

        case kNOTOP:
            yylval.op = kNPS_NOT;
            break;
    }

    return tokn;
}


/*------------------------------------------------------------------------*/
/** シンボルトークンの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makesymbol(char *s, bool trunc)
{
    if (trunc)
    {
        s = lex_escapestr(lex_truncstr(s));
    }
    else
    {
        int	tokn;
        int	wlen;

        wlen = sizeof(reserved_words) / sizeof(keyword_t);
        tokn = lookup_words(reserved_words, wlen, s);

        if (tokn != -1)
            return lex_update_tokenpos(lex_reserveword(tokn, s));
    }

    yylval.obj = NewtMakeSymbol(s);
    lex_debug(kSYMBOL);

	return lex_update_tokenpos(kSYMBOL);
}


/*------------------------------------------------------------------------*/
/** 文字列トークンの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makestring(char *s, bool trunc)
{
    if (trunc)
        s = lex_escapestr(lex_truncstr(s));

    yylval.obj = NewtMakeString(s, true);
    lex_debug(kSTRING);

	return lex_update_tokenpos(kSTRING);
}


/*------------------------------------------------------------------------*/
/** 正規表現トークンの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makeregex(char *s, bool trunc)
{
    if (trunc)
        s = lex_escapestr(lex_truncstr(s));

    yylval.obj = NewtMakeString(s, true);
    lex_debug(kREGEX);

	return lex_update_tokenpos(kREGEX);
}


/*------------------------------------------------------------------------*/
/** 文字トークンの作成
 *
 * @param c			[in] 文字
 *
 * @return			トークンID
 */

int lex_makechar(int c)
{
    yylval.obj = NewtMakeCharacter(c);
    lex_debug(kCHARACTER);

	return lex_update_tokenpos(kCHARACTER);
}


/*------------------------------------------------------------------------*/
/** Make a special code (this is similar to a character, and it is needed
 * as a function signature for newer .pkg files)
 *
 * @param c            [in] special value
 *
 * @return            Special Ref
 */

int lex_makespecial(int c)
{
    yylval.obj = NewtMakeSpecial(c);
    lex_debug(kSPECIAL);

    return lex_update_tokenpos(kSPECIAL);
}


/*------------------------------------------------------------------------*/
/** 整数トークンの作成
 *
 * @param n			[in] 整数
 *
 * @return			トークンID
 */

int lex_makeinteger(int64_t n)
{
    yylval.obj = NewtMakeInteger(n);
    lex_debug(kINTEGER);

	return lex_update_tokenpos(kINTEGER);
}


/*------------------------------------------------------------------------*/
/** 浮動小数点トークンの作成
 *
 * @param n			[in] 浮動小数点
 *
 * @return			トークンID
 */

int lex_makereal(double n)
{
    yylval.obj = NewtMakeReal(n);
    lex_debug(kREAL);

	return lex_update_tokenpos(kREAL);
}


#ifdef __NAMED_MAGIC_POINTER__

/*------------------------------------------------------------------------*/
/** 名前付マジックポインタの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makenamedmp(char *s, bool trunc)
{
	int		pos;

    if (trunc)
    {
        s = lex_escapestr(lex_truncstr(s));
    }

    yylval.obj = NewtMakeNamedMP(s);
    lex_debug(kMAGICPOINTER);

	pos = lex_update_tokenpos(kMAGICPOINTER);

	// NOS2 非互換
	WORN_NOS2("Named Magic Pointer");

	return pos;
}

#else

/*------------------------------------------------------------------------*/
/** 名前付マジックポインタの作成
 *
 * @param s			[in] 文字列
 * @param trunc		[in] 前後の切り詰め
 *
 * @return			トークンID
 */

int lex_makenamedmp(char *s, bool trunc)
{
	return lex_update_tokenpos(kERROR);
}

#endif


/*------------------------------------------------------------------------*/
/** マジックポインタトークンの作成
 *
 * @param n			[in] マジックポインタ番号
 *
 * @return			トークンID
 */

int lex_makemagicpointer(int n)
{
	if (0x03ff < n)
	{	// 数値が範囲外
		return lex_update_tokenpos(kERROR);
	}

	yylval.obj = NewtMakeMagicPointer(0, n);
    lex_debug(kMAGICPOINTER);

	return lex_update_tokenpos(kMAGICPOINTER);
}


#if 0
#pragma mark -
#endif
/*------------------------------------------------------------------------*/
/** デバッグ表示
 *
 * @param type		[in] トークンID
 *
 * @return			なし
 */

void lex_debug(int type)
{
    char *	name = "unknown";

    if (! NEWT_DUMPLEX)
        return;

    switch (type)
    {
        case kSYMBOL:
            name = "symbol";
            break;

        case kSTRING:
            name = "string";
            break;

        case kINTEGER:
            name = "integer";
            break;

        case kREAL:
            name = "real";
            break;

		case kMAGICPOINTER:
            name = "magic pointer";
			break;
    }

    NewtFprintf(stderr, "  %s\t==> ", name);
    NewtPrintObject(stderr, yylval.obj);
}

#if 0
#pragma mark -
#endif
//--------------------------------------------------------------------------
/**
 * Include a file into the source code.
 */
int lex_include_file(char *filename)
{
    FILE *	f;

    BEGIN INITIAL;
    filename++; filename[strlen(filename)-1]=0;
    if (include_stack_ptr>=MAX_INCLUDE_DEPTH) {
        NPSErrorStr('E', "include: nested too deeply");
        return lex_update_tokenpos(0);
    }
    f = fopen( filename, "rb" );
    if (!f) {
        char msg[256];
        snprintf(msg, sizeof(msg), "include: %s: %s", filename, strerror(errno));
        NPSErrorStr('E', msg);
        return lex_update_tokenpos(0);
    }
    include_files[include_stack_ptr] = yyin;
    include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
    yyin = f;

    yy_switch_to_buffer(
        yy_create_buffer( yyin, YY_BUF_SIZE )
    );

    return lex_update_tokenpos(0);
}

/**
 * The include has no filename in double quotes. Report a syntax error; the
 * rule skips the rest of the line, and parsing goes on so that later errors
 * are reported too. Nothing was pushed on the include stack.
 */
void lex_include_invalid_filename()
{
    NPSErrorStr('E', "include: invalid filename");
}

/**
 * We reached the end of the current file; unroll the include stack and terminate
 * if there are no more files.
 *
 * @return 0 if there are no more files on the stack and we should terminate
 */
int lex_include_done()
{
    if ( include_stack_ptr == 0 )
        yyterminate(); // this macro returns 0!
    lex_include_pop();
    return 1;
}

/**
 * Close the current included file and go back to the one that included it.
 */
void lex_include_pop(void)
{
    fclose(yyin);
    yy_delete_buffer( YY_CURRENT_BUFFER );
    yy_switch_to_buffer( include_stack[--include_stack_ptr] );
    yyin = include_files[include_stack_ptr];
}

#if 0
#pragma mark -
#endif
//--------------------------------------------------------------------------

int lex_set_line(char *s)
{
    nps_env.lineno = atoi(s);
    BEGIN INITIAL;
    return lex_update_tokenpos(0);
}

void lex_invalid_line(void)
{
    NPSErrorStr('E', "line: invalid format");
}

#if 0
#pragma mark -
#endif
//--------------------------------------------------------------------------
/** 字句解析のための初期化
 *
 * @return			なし
 */

void nps_yyinit(void)
{
	static bool inited = 0; // was "false"

	if (! inited)
	{   //単語テーブルのソート
		lookup_sorttable(reserved_words, sizeof(reserved_words) / sizeof(keyword_t));
		lookup_sorttable(operator_words, sizeof(operator_words) / sizeof(keyword_t));

		inited = true;
	}
}


//--------------------------------------------------------------------------
/** 字句解析の後始末
 *
 * @return			なし
 */

int nps_yycleanup(void)
{
	// A parse can stop inside an included file.
	while (0 < include_stack_ptr)
		lex_include_pop();
	BEGIN INITIAL;
	YY_FLUSH_BUFFER;
    memset(nps_env.linebuf, '\0', sizeof(nps_env.linebuf));
	yyterminate();
}

